application: bmpence
version: 0.1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/.+ 
  script: handle_mail.py 
  login: admin

- url: /static
  static_dir: static

- url: /.*
  script: handle_web.py
  login: admin

inbound_services:
- mail
