application: dontspamme
version: 1
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: gaeunit.py    
    
- url: /_ah/mail/.+ 
  script: dontspamme/mail/handler.py
  login: admin

- url: /static
  static_dir: dontspamme/web/static

- url: /.*
  script: dontspamme/web/handler.py
  login: required
  secure: always

inbound_services:
- mail
