application: <<APP_ID>>
version: <<APP_VERSION>>
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/.+ 
  script: dontspamme/mail/handler.py
  login: admin

- url: /static
  static_dir: dontspamme/web/static

- url: /api/.+
  script: dontspamme/web/api/mapping.py
  login: required
  secure: always

- url: /api/
  script: dontspamme/web/api/authenticate.py

- url: /.*
  script: dontspamme/web/handler.py
  login: required
  secure: always

inbound_services:
- mail
